/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SEED = 128h843233523a613966423b622562592c62
*/
module rand_increment_3 (
    input clk,
    input rst,
    output reg [1:0] out
  );
  
  localparam SEED = 128'h843233523a613966423b622562592c62;
  
  
  wire [1-1:0] M_edge_detector_rng_out;
  reg [1-1:0] M_edge_detector_rng_in;
  edge_detector_13 edge_detector_rng (
    .clk(clk),
    .in(M_edge_detector_rng_in),
    .out(M_edge_detector_rng_out)
  );
  wire [1-1:0] M_edge_detector_seed_out;
  reg [1-1:0] M_edge_detector_seed_in;
  edge_detector_13 edge_detector_seed (
    .clk(clk),
    .in(M_edge_detector_seed_in),
    .out(M_edge_detector_seed_out)
  );
  reg [2:0] M_seed_d, M_seed_q = 1'h0;
  wire [1-1:0] M_slowerclock_value;
  counter_12 slowerclock (
    .clk(clk),
    .rst(rst),
    .value(M_slowerclock_value)
  );
  wire [32-1:0] M_random_number_num;
  reg [1-1:0] M_random_number_next;
  reg [32-1:0] M_random_number_seed;
  pn_gen_14 random_number (
    .clk(clk),
    .rst(rst),
    .next(M_random_number_next),
    .seed(M_random_number_seed),
    .num(M_random_number_num)
  );
  
  reg [1:0] temp_pointer;
  
  always @* begin
    M_seed_d = M_seed_q;
    
    out = 1'h0;
    M_random_number_next = 1'h0;
    M_random_number_seed = M_seed_q;
    M_edge_detector_rng_in = M_slowerclock_value;
    M_random_number_next = M_edge_detector_rng_out;
    M_edge_detector_seed_in = M_slowerclock_value;
    temp_pointer = M_random_number_num[0+1-:2];
    if (M_edge_detector_seed_out) begin
      M_seed_d = M_seed_q + 1'h1;
    end
    
    case (M_random_number_num[0+1-:2])
      2'h0: begin
        out = 2'h0;
      end
      2'h1: begin
        out = 2'h1;
      end
      2'h2: begin
        out = 2'h2;
      end
      2'h3: begin
        out = 2'h3;
      end
    endcase
  end
  
  always @(posedge clk) begin
    M_seed_q <= M_seed_d;
  end
  
endmodule
